name: glva_analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.9
  - papermill
  - nbconvert
  - jupyter
  - mdanalysis
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - pymol
